# hostname prefix:
app.service=restexamplev001
# context: in pom.xml <springpr.app.id>springpr-data-relational-example</springpr.app.id>
# health URIs: .helm/values_e1.yaml

# logging
# debug=true
logging.level.root=INFO

# Virtual Thread
spring.threads.virtual.enabled=false
spring.task.execution.simple.concurrency-limit=-1
spring.task.scheduling.simple.concurrency-limit=1001
server.tomcat.threads.max=200

# CORS support
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=*

VAULT_DEMO_USERNAME=SHOULD_SET_USERNAME_VALUE_IN_VALULT
VAULT_DEMO_PROPERTY=SHOULD_SET_PROPERTY_VALUE_IN_VALULT

### OpenTelemetry
otel.springboot.resource.attributes.deployment.environment=E1

#otel.exporter.otlp.endpint=https://otel.springpr.dev

### Micrometer Metrics ###
management.otlp.metrics.export.url=https://otel.springpr.dev/ot/v1/metrics
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.step=1m

management.observations.enable.all=true
# springdoc.paths-to-match=/variables/**,/api/v1/employees/**
