spring.config.import=\
    classpath:default/actuator.properties,\
    classpath:default/app-info.properties,\
    classpath:default/build-info.properties,\
    classpath:default/concurrency.properties,\
    classpath:default/jackson.properties,\
    classpath:default/openapi.properties,\
    classpath:default/otel.properties,\
    classpath:default/spring.properties,\
    classpath:default/spring-data-rest.properties,\
    classpath:default/springpr-common.properties,\

######################
### Server Properties ###
######################
### logging levels ###
# Default Logging
logging.level.root=INFO
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#logging.level.org.springframework.data.cassandra.core.cql.CqlTemplate=DEBUG
#logging.level.com.datastax.driver.core.QueryLogger.NORMAL=DEBUG
#logging.level.com.datastax.driver.core.QueryLogger.SLOW=TRACE

### Default Server ###
## Server properties
server.port=8080
server.shutdown=graceful

### Context Path ###
# server.servlet.context-path=/abc
