server.port=8080

# expose metrics in prometheus format
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.info.git.mode=simple
