<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-dependencies</artifactId>
    <version>3.5.7</version>
  </parent>

  <groupId>org.springpr.springpr</groupId>
  <artifactId>springpr-parent</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>

  <name>Paved Road for Spring Boot Based Applications - Parent Root</name>
  <description>See README.md</description>

  <!-- common build environment settings -->
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://opensource.aexp.com/LICENSE.txt</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <name>springpr136@gmail.com</name>
    </developer>
  </developers>

  <modules>
    <module>springpr-parent-bom</module>
    <module>springpr-common</module>
    <module>springpr-batch</module>
    <module>springpr-rest-interface</module>
    <module>springpr-rest</module>
    <module>springpr-data-relational</module>
    <module>springpr-jwt</module>
    <module>springpr-webclient</module>
    <module>springpr-grpc</module>
    <module>springpr-resiliency</module>
    <module>springpr-nms4jadaptor</module>
    <module>springpr-couchbase</module>
    <module>springpr-yugabytedb</module>
    <module>springpr-cassandra</module>
    <!--
    <module>springpr-batch-file</module>
    <module>springpr-jooq</module>
    <module>springpr-kafka</module>
    -->
  </modules>

  <!-- common build properties -->
  <properties>
    <!-- /-/-release option of the javac compiler -->
    <java.release.version>21</java.release.version>
    <spring-boot.version>3.5.7</spring-boot.version>
    <!-- ### ### ### project version ### ### ### -->
    <revision>${spring-boot.version}.${java.release.version}.7-SNAPSHOT</revision>

    <springpr.app.id>${project.artifactId}</springpr.app.id>

    <java.compatible.versions>[${java.release.version}, 26)</java.compatible.versions>
    <maven.compatible.versions>[3.6.3, 4.0.0)</maven.compatible.versions>

    <!-- maven-compiler-plugin: source and target have been replaced by release -->
    <maven.compiler.source>${java.release.version}</maven.compiler.source>
    <maven.compiler.target>${java.release.version}</maven.compiler.target>
    <maven.compiler.release>${java.release.version}</maven.compiler.release>

    <maven.build.timestamp.format>yyyy-MM-dd_HH-mm-ss</maven.build.timestamp.format>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

    <hydra.build.directory>${project.build.directory}</hydra.build.directory>

    <flag.allowSnapshots>true</flag.allowSnapshots>

    <!-- ############################################################ -->
    <!-- springpr dependencies not managed by spring-boot-dependencies -->
    <!-- ############################################################ -->
    <!-- springpr-parent -->
    <opentelemetry-instrumentation-bom.version>2.21.0</opentelemetry-instrumentation-bom.version>
    <!-- springpr-common/springpr-couchbase -->
    <opentelemetry-samplers.version>1.51.0-alpha</opentelemetry-samplers.version>
    <error-handling-spring-boot-starter.version>4.6.0</error-handling-spring-boot-starter.version>
    <springdoc-openapi-starter-common.version>2.8.13</springdoc-openapi-starter-common.version>
    <wiremock.version>3.13.1</wiremock.version>
    <!-- springpr-batch -->
    <spring-cloud-dependencies.version>2025.0.0</spring-cloud-dependencies.version>
    <spring-cloud-dataflow-apps-metadata-plugin.version>1.1.2</spring-cloud-dataflow-apps-metadata-plugin.version>
    <!-- springpr-data-relational -->
    <datasource-micrometer-spring-boot.version>1.2.0</datasource-micrometer-spring-boot.version>
    <jdbc-yugabytedb.version>42.7.3-yb-4</jdbc-yugabytedb.version>

    <!-- ##################################################### -->
    <!-- Maven Plugins not managed by spring-boot-dependencies -->
    <!-- ##################################################### -->
    <flatten-maven-plugin.version>1.7.3</flatten-maven-plugin.version>
    <google-java-format.version>1.30.0</google-java-format.version>
    <jacoco-maven-plugin.version>0.8.14</jacoco-maven-plugin.version>
    <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
    <lombok-maven-plugin.version>1.18.20.0</lombok-maven-plugin.version>
    <spotless-maven-plugin.version>3.0.0</spotless-maven-plugin.version>

    <!-- temporary overwrite -->
    <testcontainers-bom.version>2.0.1</testcontainers-bom.version>

    <!-- latest version 6.22.1 -->
    <rewrite-maven-plugin.version>6.21.1</rewrite-maven-plugin.version>

    <rewrite-analysis.version>2.28.0</rewrite-analysis.version>
    <rewrite-all.version>1.22.2</rewrite-all.version>
    <rewrite-devcenter.version>1.10.1</rewrite-devcenter.version>
    <rewrite-jackson.version>1.8.0</rewrite-jackson.version>
    <rewrite-joda.version>0.2.1</rewrite-joda.version>
    <rewrite-migrate-java.version>3.20.0</rewrite-migrate-java.version>
    <rewrite-logging-frameworks.version>3.17.0</rewrite-logging-frameworks.version>
    <rewrite-rewrite.version>0.14.1</rewrite-rewrite.version>
    <rewrite-spring.version>6.17.0</rewrite-spring.version>
    <rewrite-static-analysis.version>2.20.0</rewrite-static-analysis.version>

    <!-- temporarily skip it-commit-id-maven-plugin if github is not available -->
    <git-commit-id-maven-plugin.skip>true</git-commit-id-maven-plugin.skip>
    <!-- temporarily skip code formatting -->
    <spotless-maven-plugin.skip>false</spotless-maven-plugin.skip>

  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.openrewrite</groupId>
        <artifactId>rewrite-bom</artifactId>
        <version>8.64.0</version>
        <type>pom</type>
        <scope>provided</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.cyclonedx</groupId>
          <artifactId>cyclonedx-maven-plugin</artifactId>
          <executions>
            <execution>
              <goals>
                <goal>makeAggregateBom</goal>
              </goals>
              <phase>generate-resources</phase>
              <configuration>
                <projectType>application</projectType>
                <outputDirectory>${project.build.outputDirectory}/META-INF/sbom</outputDirectory>
                <outputFormat>json</outputFormat>
                <outputName>application.cdx</outputName>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>flatten-maven-plugin</artifactId>
          <version>${flatten-maven-plugin.version}</version>
          <configuration>
            <updatePomFile>true</updatePomFile>
            <flattenMode>resolveCiFriendliesOnly</flattenMode>
          </configuration>
          <executions>
            <execution>
              <id>flatten</id>
              <goals>
                <goal>flatten</goal>
              </goals>
              <phase>process-resources</phase>
            </execution>
            <execution>
              <id>flatten.clean</id>
              <goals>
                <goal>clean</goal>
              </goals>
              <phase>clean</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>io.github.git-commit-id</groupId>
          <artifactId>git-commit-id-maven-plugin</artifactId>
          <configuration>
            <skip>${git-commit-id-maven-plugin.skip}</skip>
            <generateGitPropertiesFile>true</generateGitPropertiesFile>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>revision</goal>
              </goals>
              <phase>validate</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>${jacoco-maven-plugin.version}</version>
          <configuration>
            <excludes>
              <exclude>**/Application.class</exclude>
              <exclude>**/*Controller.class</exclude>
              <exclude>**/*Validator.class</exclude>
            </excludes>
          </configuration>
          <executions>
            <execution>
              <id>prepare-agent</id>
              <goals>
                <goal>prepare-agent</goal>
              </goals>
            </execution>
            <execution>
              <id>report</id>
              <goals>
                <goal>report</goal>
              </goals>
              <phase>package</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.projectlombok</groupId>
          <artifactId>lombok-maven-plugin</artifactId>
          <version>${lombok-maven-plugin.version}</version>
          <executions>
            <execution>
              <goals>
                <goal>delombok</goal>
              </goals>
              <phase>generate-sources</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <executions>
            <execution>
              <id>make-assembly</id>
              <goals>
                <goal>single</goal>
              </goals>
              <phase>package</phase>
              <configuration>
                <appendAssemblyId>false</appendAssemblyId>
                <tarLongFileMode>posix</tarLongFileMode>
                <descriptors>
                  <descriptor>${project.basedir}/assembly.xml</descriptor>
                </descriptors>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <configuration>
            <encoding>UTF-8</encoding>
            <annotationProcessorPaths>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
              </path>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-mapstruct-binding</artifactId>
                <version>${lombok-mapstruct-binding.version}</version>
              </path>
            </annotationProcessorPaths>
            <compilerArgs>
              <arg>-parameters</arg>
            </compilerArgs>
            <release>${java.release.version}</release>
          </configuration>
          <executions>
            <execution>
              <id>generate-log4j-plugin-descriptor</id>
              <goals>
                <goal>compile</goal>
              </goals>
              <phase>process-classes</phase>
              <configuration>
                <proc>only</proc>
                <annotationProcessorPaths>
                  <path>
                    <groupId>org.apache.logging.log4j</groupId>
                    <artifactId>log4j-core</artifactId>
                    <version>${log4j2.version}</version>
                  </path>
                  <path>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok-mapstruct-binding</artifactId>
                    <version>0.2.0</version>
                  </path>
                </annotationProcessorPaths>
                <annotationProcessors>
                  <!-- Process sources using `org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor` to generate `Log4j2Plugins.dat` -->
                  <processor>org.apache.logging.log4j.core.config.plugins.processor.PluginProcessor</processor>
                </annotationProcessors>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <configuration>
            <rules>
              <banDuplicatePomDependencyVersions></banDuplicatePomDependencyVersions>
              <requireJavaVersion>
                <version>${java.compatible.versions}</version>
              </requireJavaVersion>
              <requireMavenVersion>
                <version>${maven.compatible.versions}</version>
              </requireMavenVersion>
              <requireProperty>
                <property>spring-boot.version</property>
                <message>spring-boot.version should be defined!</message>
                <regex>.*\d.*</regex>
                <regexMessage>The spring-boot.version must contain at least one digit.</regexMessage>
              </requireProperty>
              <bannedPlugins>
                <!-- will only display a warning but does not fail the build. -->
                <level>WARN</level>
                <excludes>
                  <exclude>org.apache.maven.plugins:maven-verifier-plugin</exclude>
                </excludes>
                <message>Please consider using the maven-invoker-plugin (http://maven.apache.org/plugins/maven-invoker-plugin/)!</message>
              </bannedPlugins>
              <banDynamicVersions>
                <ignores>
                  <ignore>package.to.be.ignored</ignore>
                </ignores>
                <allowSnapshots>${flag.allowSnapshots}</allowSnapshots>
                <excludedScopes>test</excludedScopes>
              </banDynamicVersions>
              <requireFilesExist>
                <files>
                  <file>${project.basedir}/.springpr/buildblocks.yaml</file>
                  <file>${project.basedir}/.mvn/jvm.config</file>
                  <file>${project.basedir}/lombok.config</file>
                </files>
              </requireFilesExist>
            </rules>
          </configuration>
          <executions>
            <execution>
              <id>enforce-rules</id>
              <goals>
                <goal>enforce</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <configuration>
            <skipTests>false</skipTests>
            <testFailureIgnore>true</testFailureIgnore>
            <forkCount>1</forkCount>
            <argLine>@{argLine}
            -Xmx1024m
            -XX:MaxMetaspaceSize=512m
            -XX:+EnableDynamicAgentLoading
            -javaagent:${settings.localRepository}/org/mockito/mockito-core/${mockito.version}/mockito-core-${mockito.version}.jar
            -Xshare:off
            -Djavax.net.ssl.trustStore=${env.JAVA_CERTS}</argLine>
            <systemPropertyVariables>
              <javax.net.ssl.trustStorePassword>changeit</javax.net.ssl.trustStorePassword>
              <jdk.internal.httpclient.disableHostnameVerification>true</jdk.internal.httpclient.disableHostnameVerification>
              <jdk.instrument.traceUsage></jdk.instrument.traceUsage>
            </systemPropertyVariables>
            <excludes>
              <exclude>*Validation.java</exclude>
              <exclude>org.springpr.springpr.base.retry.*.java</exclude>
            </excludes>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <configuration>
            <encoding>UTF-8</encoding>
            <escapeString>\</escapeString>
          </configuration>
          <executions>
            <execution>
              <id>copy-jar</id>
              <goals>
                <goal>copy-resources</goal>
              </goals>
              <phase>package</phase>
              <configuration>
                <outputDirectory>${hydra.build.directory}/appBundle</outputDirectory>
                <resources>
                  <resource>
                    <filtering>false</filtering>
                    <directory>${hydra.build.directory}</directory>
                    <includes>
                      <include>*.jar</include>
                    </includes>
                  </resource>
                </resources>
              </configuration>
            </execution>
            <execution>
              <id>copy-config</id>
              <goals>
                <goal>copy-resources</goal>
              </goals>
              <phase>package</phase>
              <configuration>
                <outputDirectory>${hydra.build.directory}/appBundle/.openshift</outputDirectory>
                <resources>
                  <resource>
                    <directory>.openshift</directory>
                    <filtering>true</filtering>
                  </resource>
                </resources>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>com.diffplug.spotless</groupId>
          <artifactId>spotless-maven-plugin</artifactId>
          <version>${spotless-maven-plugin.version}</version>
          <configuration>
            <!-- optional: limit format enforcement to just the files changed by this feature branch
        <ratchetFrom>origin/main</ratchetFrom> -->
            <skip>${spotless-maven-plugin.skip}</skip>
            <formats>
              <!-- you can define as many formats as you want, each is independent -->
              <format>
                <!-- define the files to apply to -->
                <includes>
                  <include>.gitignore</include>
                  <include>Jenkinsfile</include>
                  <include>jvm.config</include>
                  <include>**/*.md</include>
                  <include>**/*.xml</include>
                  <include>**/*.yaml</include>
                  <include>**/*.yml</include>
                </includes>
                <excludes>
                  <exclude>pom.xml</exclude>
                  <exclude>.flattened-pom.xml</exclude>
                  <exclude>**/target/**/*</exclude>
                  <exclude>.idea/**</exclude>
                  <exclude>.git/**</exclude>
                  <exclude>.openshift/**</exclude>
                  <exclude>setup/**</exclude>
                  <exclude>bin/**</exclude>
                </excludes>

                <!-- define the steps to apply to those files -->
                <trimTrailingWhitespace></trimTrailingWhitespace>
                <endWithNewline></endWithNewline>
                <indent>
                  <spaces>true</spaces>
                  <spacesPerTab>4</spacesPerTab>
                </indent>

                <replace>
                  <!-- specify replacements using search and replace -->
                  <name>Say Hello to Mars</name>
                  <search>Mars</search>
                  <replacement>Mars</replacement>
                </replace>

                <replaceRegex>
                  <!-- specify replacements using regex match and replace -->
                  <name>Say Hello to Mars from Regex</name>
                  <searchRegex>(Hello) W[a-z]{3}d</searchRegex>
                  <replacement>$1 Mars</replacement>
                </replaceRegex>
              </format>
            </formats>
            <!-- define a language-specific format -->
            <pom>
              <!-- These are the defaults, you can override if you want -->
              <includes>
                <include>pom.xml</include>
              </includes>
              <sortPom>
                <encoding>UTF-8</encoding>
                <!-- The encoding of the pom files -->
                <lineSeparator>${line.separator}</lineSeparator>
                <!-- line separator to use -->
                <expandEmptyElements>true</expandEmptyElements>
                <!-- Should empty elements be expanded-->
                <spaceBeforeCloseEmptyElement>false</spaceBeforeCloseEmptyElement>
                <!-- Should a space be added inside self-closing elements-->
                <keepBlankLines>true</keepBlankLines>
                <!-- Keep empty lines -->
                <nrOfIndentSpace>2</nrOfIndentSpace>
                <!-- Indentation -->
                <indentBlankLines>false</indentBlankLines>
                <!-- Should empty lines be indented -->
                <indentSchemaLocation>false</indentSchemaLocation>
                <!-- Should schema locations be indended -->
                <predefinedSortOrder>recommended_2008_06</predefinedSortOrder>
                <!-- Sort order of elements: https://github.com/Ekryd/sortpom/wiki/PredefinedSortOrderProfiles-->
                <sortOrderFile></sortOrderFile>
                <!-- Custom sort order of elements: https://raw.githubusercontent.com/Ekryd/sortpom/master/sorter/src/main/resources/custom_1.xml -->
                <sortDependencies></sortDependencies>
                <!-- Sort dependencies: https://github.com/Ekryd/sortpom/wiki/SortDependencies-->
                <sortDependencyExclusions></sortDependencyExclusions>
                <!-- Sort dependency exclusions: https://github.com/Ekryd/sortpom/wiki/SortDependencies-->
                <sortPlugins></sortPlugins>
                <!-- Sort plugins: https://github.com/Ekryd/sortpom/wiki/SortPlugins -->
                <sortProperties>false</sortProperties>
                <!-- Sort properties -->
                <sortModules>false</sortModules>
                <!-- Sort modules -->
                <sortExecutions>false</sortExecutions>
                <!-- Sort plugin executions -->
              </sortPom>
            </pom>

            <java>
              <!-- These are the defaults, you can override if you want -->
              <includes>
                <include>src/main/java/**/*.java</include>
                <include>src/test/java/**/*.java</include>
              </includes>

              <!-- apply a specific flavor of google-java-format and reflow long strings -->
              <googleJavaFormat>
                <version>${google-java-format.version}</version>
                <style>AOSP</style>
                <reflowLongStrings>true</reflowLongStrings>
              </googleJavaFormat>

              <importOrder>
                <!-- or a custom ordering -->
                <wildcardsLast>true</wildcardsLast>
                <!-- Optional, default false. Sort wildcard import after specific imports -->
                <order>java|javax,org,com,,org.springpr,\#,\#org.springpr</order>
                <!-- or use <file>${project.basedir}/eclipse.importorder</file> -->
                <!-- you can use an empty string for all the imports you didn't specify explicitly,
                   '|' to join group without blank line, and '\#` prefix for static imports. -->
              </importOrder>

              <!-- self-explanatory -->
              <removeUnusedImports></removeUnusedImports>
              <forbidWildcardImports></forbidWildcardImports>

              <formatAnnotations></formatAnnotations>
              <!-- fixes formatting of type annotations, see below -->

              <!-- make sure every file has the following copyright header.
                 optionally, Spotless can set copyright years by digging
                 through git history (see "license" section below) -->
              <licenseHeader>
                <content>/* (C)$YEAR */</content>
                <!-- or <file>${project.basedir}/license-header</file> -->
              </licenseHeader>
            </java>

            <json>
              <includes>
                <!-- You have to set the target manually -->
                <include>src/**/*.json</include>
              </includes>

              <trimTrailingWhitespace></trimTrailingWhitespace>
              <endWithNewline></endWithNewline>
              <indent>
                <spaces>true</spaces>
                <spacesPerTab>4</spacesPerTab>
              </indent>
              <jackson>
                <features>
                  <!-- optional: Customize the set of features (based on com.fasterxml.jackson.databind.SerializationFeature) -->
                  <INDENT_OUTPUT>true</INDENT_OUTPUT>
                  <!-- true by default -->
                  <ORDER_MAP_ENTRIES_BY_KEYS>false</ORDER_MAP_ENTRIES_BY_KEYS>
                  <!-- false by default -->
                </features>
              </jackson>
            </json>

            <sql>
              <!-- You have to set the target manually -->
              <includes>
                <include>src/main/**/*.sql</include>
              </includes>

              <trimTrailingWhitespace></trimTrailingWhitespace>
              <endWithNewline></endWithNewline>
              <indent>
                <spaces>true</spaces>
                <spacesPerTab>4</spacesPerTab>
              </indent>

              <dbeaver>
                <!-- optional 
              <configFile>dbeaver.properties</configFile>
              -->
              </dbeaver>
            </sql>

          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>check</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <configuration>
            <mainClass>${start-class}</mainClass>
            <excludeDevtools>false</excludeDevtools>
            <jvmArguments>-Djavax.net.ssl.trustStore=${env.JAVA_CERTS} -Djavax.net.ssl.trustStorePassword=changeit</jvmArguments>
          </configuration>
          <executions>
            <execution>
              <id>spring-boot</id>
              <goals>
                <goal>build-info</goal>
                <goal>repackage</goal>
              </goals>
              <phase>install</phase>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.openrewrite.maven</groupId>
          <artifactId>rewrite-maven-plugin</artifactId>
          <version>${rewrite-maven-plugin.version}</version>
          <configuration>
            <exportDatatables>true</exportDatatables>
            <activeRecipes>
              <!-- rewrite-all -->
              <!-- * counts the number of lines of the various kinds of source code and data formats. -->
              <recipe>org.openrewrite.LanguageComposition</recipe>

              <!-- rewrite-devcenter -->
              <!-- * A collection of recipes that apply best practices to Maven POMs. -->
              <recipe>io.moderne.devcenter.ApacheMavenBestPractices</recipe>
              <!-- * Move to JUnit Jupiter. -->
              <recipe>io.moderne.devcenter.JUnitJupiterUpgrade</recipe>
              <!-- * reveal common OWASP Top 10 issues in your source code. -->
              <recipe>io.moderne.devcenter.SecurityStarter</recipe>
              <!-- * List out the contents of each unique GitProvenance marker in the set of source files. -->
              <recipe>org.openrewrite.FindGitProvenance</recipe>
              <recipe>org.openrewrite.FindLstProvenance</recipe>

              <!-- rewrite-joda -->
              <recipe>org.openrewrite.java.joda.time.NoJodaTime</recipe>
              <recipe>org.openrewrite.java.joda.time.JodaTimeRecipe</recipe>

              <!-- rewrite-logging-frameworks -->
              <!-- * Applies best practices to logging with SLF4J. -->
              <recipe>org.openrewrite.java.logging.slf4j.Slf4jBestPractices</recipe>

              <!-- rewrite-migrate-java -->
              <recipe>org.openrewrite.java.AddApache2LicenseHeader</recipe>
              <!-- * Apply JSpecify best practices, such as migrating off of alternatives, and adding missing @Nullable annotations. -->
              <recipe>org.openrewrite.java.jspecify.MigrateFromSpringFrameworkAnnotations</recipe>
              <recipe>org.openrewrite.java.jspecify.JSpecifyBestPractices</recipe>
              <!-- * Add the lombok-mapstruct-binding annotation processor as needed when both MapStruct and Lombok are used. -->
              <recipe>org.openrewrite.java.migrate.AddLombokMapstructBinding</recipe>
              <!-- * Applies all recipes that enforce best practices for using Lombok. -->
              <recipe>org.openrewrite.java.migrate.lombok.LombokBestPractices</recipe>

              <recipe>org.openrewrite.java.migrate.util.JavaUtilAPIs</recipe>
              <recipe>org.openrewrite.java.migrate.UpgradeToJava21</recipe>

              <!-- rewrite-rewrite -->
              <!-- ** Best practices for OpenRewrite recipe development. -->
              <recipe>org.openrewrite.recipes.rewrite.OpenRewriteRecipeBestPractices</recipe>
              -
              <!-- rewrite-spring -->
              <recipe>org.openrewrite.java.spring.batch.SpringBatch4To5Migration</recipe>
              <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_5</recipe>

              <recipe>org.openrewrite.java.spring.framework.BeanMethodsNotPublic</recipe>
              <recipe>org.openrewrite.java.spring.NoAutowiredOnConstructor</recipe>
              <recipe>org.openrewrite.java.spring.PropertiesToKebabCase</recipe>
              <recipe>org.openrewrite.java.springdoc.SwaggerToSpringDoc</recipe>

              <!-- rewrite-static-analysis -->
              <recipe>org.openrewrite.staticanalysis.CodeCleanup</recipe>
              <recipe>org.openrewrite.staticanalysis.CommonStaticAnalysis</recipe>

              <!-- rewrite-testing-frameworks -->
              <!-- * Applies best practices to tests. -->
              <recipe>org.openrewrite.java.testing.junit5.JUnit5BestPractices</recipe>
              <recipe>org.openrewrite.java.testing.mockito.MockitoBestPractices</recipe>
              <recipe>org.openrewrite.java.testing.testcontainers.TestContainersBestPractices</recipe>

              <!-- 
              - rewrite-analysis -
              <recipe>com.yourorg.ControlFlowVisualizationExample</recipe>
              <recipe>com.yourorg.FindFlowBetweenMethodsExample</recipe>
              <recipe>com.yourorg.FindMethodsExample</recipe>

              - * exclude dependencies from POM -
              <recipe>com.yourorg.ExcludeDependencyExample</recipe>
              - * Git source control metadata -
              <recipe>org.openrewrite.FindGitProvenance</recipe>
              <recipe>com.yourorg.UpdateMavenProjectPropertyJavaVersionExample</recipe>
              <recipe>com.yourorg.UseMavenCompilerPluginReleaseConfigurationExample</recipe>

              - rewrite-all -
              <recipe>org.openrewrite.FindCallGraph</recipe>
              <recipe>org.openrewrite.FindDuplicateSourceFiles</recipe>
              - * counts the number of lines of the various kinds of source code and data formats. -
              <recipe>org.openrewrite.LanguageComposition</recipe>

              - rewrite-jackson -
              - * Apply best practices for using Jackson library, including upgrade to Jackson 2.x and removing redundant annotations. -
              <recipe>org.openrewrite.java.jackson.JacksonBestPractices</recipe>
              <recipe>org.openrewrite.java.jackson.UpgradeJackson_2_3</recipe>

              - rewrite-migrate-java -
              <recipe>org.openrewrite.java.migrate.UpgradeToJava17</recipe>
              <recipe>org.openrewrite.java.migrate.UpgradeToJava21</recipe>
              <recipe>org.openrewrite.java.migrate.UpgradeToJava25</recipe>

              - rewrite-logging-frameworks -
              - * Applies best practices to logging with SLF4J. -
              <recipe>org.openrewrite.java.logging.slf4j.Slf4jBestPractices</recipe>
            -->
            </activeRecipes>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-all</artifactId>
              <version>${rewrite-all.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.meta</groupId>
              <artifactId>rewrite-analysis</artifactId>
              <version>${rewrite-analysis.version}</version>
            </dependency>
            <dependency>
              <groupId>io.moderne.recipe</groupId>
              <artifactId>rewrite-devcenter</artifactId>
              <version>${rewrite-devcenter.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-jackson</artifactId>
              <version>${rewrite-jackson.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-joda</artifactId>
              <version>${rewrite-joda.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-logging-frameworks</artifactId>
              <version>${rewrite-logging-frameworks.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-migrate-java</artifactId>
              <version>${rewrite-migrate-java.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-rewrite</artifactId>
              <version>${rewrite-rewrite.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-spring</artifactId>
              <version>${rewrite-spring.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-static-analysis</artifactId>
              <version>${rewrite-static-analysis.version}</version>
            </dependency>
            <dependency>
              <groupId>org.openrewrite.recipe</groupId>
              <artifactId>rewrite-testing-frameworks</artifactId>
              <version>${rewrite-migrate-java.version}</version>
            </dependency>
          </dependencies>
        </plugin>
      </plugins>
    </pluginManagement>

  </build>

  <profiles>
    <profile>
      <id>lib</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <build>
        <plugins>
          <!-- resolve Maven variables, remove build and development related elements -->
          <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>flatten-maven-plugin</artifactId>
          </plugin>
          <plugin>
            <groupId>org.openrewrite.maven</groupId>
            <artifactId>rewrite-maven-plugin</artifactId>
          </plugin>
          <!-- format only markdown/.ignore/pom.xml files -->
          <plugin>
            <groupId>com.diffplug.spotless</groupId>
            <artifactId>spotless-maven-plugin</artifactId>
            <configuration>
              <skip>${spotless-maven-plugin.skip}</skip>
              <formats>
                <!-- you can define as many formats as you want, each is independent -->
                <format>
                  <!-- define the files to apply to -->
                  <includes>
                    <include>*.md</include>
                    <include>.gitignore</include>
                  </includes>
                  <!-- define the steps to apply to those files -->
                  <trimTrailingWhitespace></trimTrailingWhitespace>
                  <endWithNewline></endWithNewline>
                  <indent>
                    <spaces>true</spaces>
                    <spacesPerTab>4</spacesPerTab>
                  </indent>
                </format>
              </formats>
              <!-- define a language-specific format -->
              <pom>
                <!-- These are the defaults, you can override if you want -->
                <includes>
                  <include>pom.xml</include>
                </includes>
                <sortPom>
                  <encoding>UTF-8</encoding>
                  <!-- The encoding of the pom files -->
                  <lineSeparator>${line.separator}</lineSeparator>
                  <!-- line separator to use -->
                  <expandEmptyElements>true</expandEmptyElements>
                  <!-- Should empty elements be expanded-->
                  <spaceBeforeCloseEmptyElement>false</spaceBeforeCloseEmptyElement>
                  <!-- Should a space be added inside self-closing elements-->
                  <keepBlankLines>true</keepBlankLines>
                  <!-- Keep empty lines -->
                  <nrOfIndentSpace>2</nrOfIndentSpace>
                  <!-- Indentation -->
                  <indentBlankLines>false</indentBlankLines>
                  <!-- Should empty lines be indented -->
                  <indentSchemaLocation>false</indentSchemaLocation>
                  <!-- Should schema locations be indended -->
                  <predefinedSortOrder>recommended_2008_06</predefinedSortOrder>
                  <!-- Sort order of elements: https://github.com/Ekryd/sortpom/wiki/PredefinedSortOrderProfiles-->
                  <sortOrderFile></sortOrderFile>
                  <!-- Custom sort order of elements: https://raw.githubusercontent.com/Ekryd/sortpom/master/sorter/src/main/resources/custom_1.xml -->
                  <sortDependencies></sortDependencies>
                  <!-- Sort dependencies: https://github.com/Ekryd/sortpom/wiki/SortDependencies-->
                  <sortDependencyExclusions></sortDependencyExclusions>
                  <!-- Sort dependency exclusions: https://github.com/Ekryd/sortpom/wiki/SortDependencies-->
                  <sortPlugins></sortPlugins>
                  <!-- Sort plugins: https://github.com/Ekryd/sortpom/wiki/SortPlugins -->
                  <sortProperties>false</sortProperties>
                  <!-- Sort properties -->
                  <sortModules>false</sortModules>
                  <!-- Sort modules -->
                  <sortExecutions>false</sortExecutions>
                  <!-- Sort plugin executions -->
                </sortPom>
              </pom>
            </configuration>
            <executions>
              <execution>
                <goals>
                  <goal>check</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
