### local dev ###
server.port=60003

# ELF attribute
otel.resource.attributes.service.name=springpr-rest
otel.resource.attributes.service.car.id=150838830
otel.resource.attributes.service.namespace=dev.springpr.springpr.rest
otel.resource.attributes.service.instance.id=${springpr.app.id}
otel.resource.attributes.deployment.environment=E0

otel.exporter.otlp.protocol=grpc
otel.exporter.otlp.endpoint=https://otel.springpr.dev

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
#logging.level.org.hibernate.SQL=INFO
