######################
### Key Properties ###
######################
## Spring Boot Starting properties
# active Spring profile, values are from Maven profile
spring.profiles.active=${springboot.profiles}
spring.application.name=${springpr.app.id}
spring.main.banner-mode=console
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=false
spring.main.keep-alive=false
## Server properties
server.port=8080
# Spring Boot debug enabled
#debug=true
#trace=true

## CORS support
#management.endpoints.web.cors.allowed-origins=https://example.com
#management.endpoints.web.cors.allowed-methods=GET,POST

## logging levels
# Default Logging
logging.level.root=INFO
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#logging.level.org.springframework.data.cassandra.core.cql.CqlTemplate=DEBUG
#logging.level.com.datastax.driver.core.QueryLogger.NORMAL=DEBUG
#logging.level.com.datastax.driver.core.QueryLogger.SLOW=TRACE

###################################
### Application Deployment Info ###
###################################
app.id=${springpr.app.id}
app.protocol=https
app.service=restexamplev001
app.domain=springpr.dev
app.env.id=dev
app.hostname=${app.service}-${app.env.id}.${app.domain}
app.port=443
app.zone.id=eusw1a4
app.zone.hostname=${app.service}-${app.env.id}${app.zone.id}.${app.domain}
springpr.openapi.server.url=${app.protocol}://${app.zone.hostname}:${app.port}

#####################################
### Spring Boot Common Properties ###
#####################################
## Threading/Virtual Threads
spring.threads.virtual.enabled=false
spring.task.execution.simple.concurrency-limit=1000
spring.task.scheduling.simple.concurrency-limit=1001
spring.task.scheduling.thread-name-prefix=task-scheduling
spring.task.execution.thread-name-prefix=task-execution
# Async Executor default valuesh, it is used by Tomcat
spring.task.execution.pool.allow-core-thread-timeout=true
spring.task.execution.pool.keep-alive=60s
spring.task.execution.pool.core-size=8
spring.task.execution.pool.max-size=16
spring.task.execution.pool.queue-capacity=3600
# Scheduled Tasks
spring.task.scheduling.pool.size=5

## Tomcat default setting
server.tomcat.accept-count=100
#server.tomcat.connection-timeout=5s
server.tomcat.max-connections=8192
server.tomcat.max-keep-alive-requests=100
server.tomcat.processor-cache=200
server.tomcat.threads.min-spare=10

### Actuator
# expose metrics in prometheus format
management.endpoint.metrics.access=UNRESTRICTED
management.endpoint.prometheus.access=UNRESTRICTED
management.info.build.enabled=true
management.info.env.enabled=true
management.info.git.mode=full
management.info.java.enabled=true
management.info.os.enabled=true

management.endpoint.health.show-details=always
management.endpoint.loggers.access=UNRESTRICTED
management.endpoints.web.base-path=/${springpr.app.id}
management.server.port=${server.port}
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.access=UNRESTRICTED
management.health.jms.enabled=true
management.jmx.metrics.export.domain=dev.springpr.springpr.${springpr.app.id}.metrics
management.metrics.tags.application=${springpr.app.id}
management.metrics.tags.region=us-phoenix
management.metrics.tags.stack=dev

management.endpoint.env.show-values=ALWAYS
management.endpoint.configprops.show-values=ALWAYS
management.endpoints.jackson.isolated-object-mapper=false
spring.jackson.serialization.INDENT_OUTPUT=true
management.metrics.distribution.percentiles-histogram.http.server.requests=false

management.health.db.enabled=true
management.health.defaults.enabled=true

# Default Server
spring.jmx.enabled=true
server.shutdown=graceful

# Context Path
# server.servlet.context-path=/abc

### OpenAPI
springdoc.api-docs.path=/${springpr.app.id}/openapi
# Specify the path of the Swagger UI
springdoc.swagger-ui.path=/${springpr.app.id}/swagger-ui
# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=true
# springdoc.use-management-port=true
# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
# management.endpoints.web.exposure.include=openapi, swagger-ui
# springdoc.paths-to-match=/variables/**,/emp/employees/**

########################
### Spring Data REST ###
########################
spring.data.rest.basePath=/api/v1
spring.data.rest.defaultPageSize=100
spring.data.rest.maxPageSize=1000
spring.data.rest.returnBodyOnCreate=true
spring.data.rest.returnBodyOnUpdate=true

## Pagination
spring.data.web.pageable.default-page-size=100
spring.data.web.pageable.max-page-size=100
# Pagination parameter customization 
# /employees?page_chunk=1&page_limit=30.
# spring.data.web.pageable.page-parameter=chunk
# spring.data.web.pageable.size-parameter=limit
# spring.data.web.pageable.prefix=page

# REST API response
server.error.include-message=ALWAYS
# server.error.whitelabel.enabled=false
error.handling.http-status-in-json-response=true
# spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES: true

#########################################
### OpenTelemetry Spring Boot Starter ###
#########################################
# OpenTelemetry could be disabled fully
otel.sdk.disabled=false
# Otel Logging
otel.instrumentation.log4j-appender.enabled=true
otel.logs.exporter=otlp
otel.exporter.otlp.logs.timeout=1s
# Otel Metrics
otel.metrics.exporter=otlp
otel.exporter.otlp.metrics.timeout=10s
otel.metric.export.interval=1m
# Otel Tracing
otel.traces.exporter=otlp
otel.traces.sampler=always_on
otel.experimental.exporter.otlp.retry.enabled=true

# ELF required attributes
# Spring Boot 3.2.x configuration
#otel.springboot.resource.attributes.service.car.id=200005782
#otel.springboot.resource.attributes.service.namespace=dev.springpr.springpr
#otel.springboot.resource.attributes.service.instance.id=${springpr.app.id}
#otel.springboot.resource.attributes.deployment.environment=E0

# Spring Boot 3.3.x configuration
otel.propagators=tracecontext,b3
otel.resource.attributes.service.name=springpr
otel.resource.attributes.service.car.id=200005782
otel.resource.attributes.service.namespace=dev.springpr.springpr
otel.resource.attributes.service.instance.id=${springpr.app.id}
otel.resource.attributes.deployment.environment=E0

management.otlp.metrics.export.base-time-unit=milliseconds
management.otlp.metrics.export.batch-size=10000
management.otlp.metrics.export.connect-timeout=10s
management.otlp.metrics.export.enabled=false
management.otlp.metrics.export.read-timeout=10s
management.otlp.metrics.export.step=1m
#management.otlp.metrics.export.url=https://otel.springpr.dev/ot/v1/metrics

# Whether auto-configuration of tracing is enabled to export and propagate traces.
management.tracing.enabled=true
management.otlp.tracing.compression=none
#management.otlp.tracing.endpoint=https://otel.springpr.dev/ot/v1/traces
management.otlp.tracing.timeout=10s
management.tracing.sampling.probability=1.0

#Otle Instrumentation
#otel.instrumentation.opentelemetry-instrumentation-annotations.exclude-methods=my.package.MyClass1[method1,method2];my.package.MyClass2[method3]
#otel.instrumentation.methods.include=my.package.MyClass1[method1,method2];my.package.MyClass2[method3]

# Whether observations starting with the specified name should be enabled. 
management.observations.enable.all=true

###################################
### info endpoints - build info ###
###################################
info.app.name=@project.name@
info.app.description=@project.description@
info.app.artifactId=@project.artifactId@
info.app.version=@project.version@
info.app.encoding=@project.build.sourceEncoding@
info.app.java.version=@java.version@
info.app.java.source=@java.version@
info.app.java.target=@java.version@

############################
### Spring PR Properties ###
############################
### SpringPR Micrometer debug properties
springpr.micrometer.interceptable-span-exporter.enabled=false
springpr.micrometer.interceptable-metric-exporter.enabled=false

### SpringPR systemMetricsScheduler properties
springpr.common.systemMetricsScheduler.enabled=true
springpr.common.systemMetricsScheduler.sampling.cron=*/10 * * * * *

# Spring PR Retry
springpr.base.retry.intialInterval=100
springpr.base.retry.maxInterval=60000
springpr.base.retry.multiplier=2
springpr.base.retry.totalRetries=16

# SpringPR asyncTaskExecutor
async.handler.concurrency=3
async.queue.capacity=3500

# SpringPR File Health Indicator
required.file.check.enabled=false
required.file.absolute.path=/Users/yli25/Downloads/STS4/springpr/${app.id}/lombok.config

# Maven inheritance test properties
maven.parent.property=${parent_property}
maven.child.property=${child_property}
