### local dev ###
server.port=60101
app.protocol=http
app.hostname=localhost
app.port=${server.port}
app.zone.hostname=${app.hostname}

# logging
# debug=true
logging.level.root=INFO

### Virtual Thread ###
spring.threads.virtual.enabled=false
# used if virtual.enabled=true
spring.task.execution.simple.concurrency-limit=1000
spring.task.scheduling.simple.concurrency-limit=1001
# used by Tomcat if virtual.enabled=false
server.tomcat.threads.max=200

### CORS support ###
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=*

### devtools ###
spring.devtools.restart.enabled=true

### Vault Health Test ###
VAULT_DEMO_USERNAME=vault_demo_username
VAULT_DEMO_PROPERTY=vault_demo_property

# ELF attribute
otel.resource.attributes.service.name=springpr-rest-interface
otel.resource.attributes.service.car.id=200005782
otel.resource.attributes.service.namespace=dev.springpr.springpr.common
otel.resource.attributes.service.instance.id=${springpr.app.id}
otel.resource.attributes.deployment.environment=E0

otel.exporter.otlp.protocol=grpc
otel.exporter.otlp.endpoint=https://otel.springpr.dev
otel.metric.export.interval=1m
otel.traces.sampler=always_on
#otel.traces.sampler=traceidratio
#otel.traces.sampler.arg=0.01

### Micrometer Metrics ###
management.otlp.metrics.export.url=https://otel.springpr.dev/ot/v1/metrics
management.otlp.metrics.export.enabled=false
management.otlp.metrics.export.step=1m

management.observations.enable.all=true
management.observations.key-values.region=us-ipc2
management.observations.key-values.stack=dev
management.observations.enable.denied.prefix=false
management.observations.enable.another.denied.prefix=false

### log details of spans/metrics data exported ###
springpr.micrometer.interceptable-span-exporter.enabled=true
springpr.micrometer.interceptable-metric-exporter.enabled=true

### Jackson JSON ###
#spring.jackson.deserialization.accept-single-value-as-array=true

### OpenAPI Document Path Filtering ###
#springdoc.paths-to-match=/variables/**,/api/employees/**,/api/v1/employees/**,/api/v1/resources/**
