#logging.level.org.springframework.data.cassandra.core.cql.CqlTemplate=DEBUG
#logging.level.com.datastax.driver.core.QueryLogger.NORMAL=DEBUG
#logging.level.com.datastax.driver.core.QueryLogger.SLOW=TRACE

springpr.config.property=test-value