#########################
### OpenAPI endpoints ###
#########################
springdoc.api-docs.path=/${springpr.app.id}/openapi
# Specify the path of the Swagger UI
springdoc.swagger-ui.path=/${springpr.app.id}/swagger-ui
# Enable or disable Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=true
#springdoc.use-management-port=true
# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
#management.endpoints.web.exposure.include=openapi, swagger-ui

### OpenAPI Document Path Filtering ###
#springdoc.paths-to-match=/variables/**,/api/employees/**,/api/v1/employees/**,/api/v1/resources/**
