#spring.datasource.yugabytedb.url=jdbc:yugabytedb://localhost:5433/yugabyte?currentSchema=springpr
#spring.datasource.yugabytedb.user=yugabyte
#spring.datasource.yugabytedb.databaseName=yugabyte
#spring.datasource.yugabytedb.schema=springpr
#spring.datasource.yugabytedb.pa$$word=
#spring.datasource.yugabytedb.driver-class-name=

spring.datasource.yugabytedb.dataSourceClassName=com.yugabyte.ysql.YBClusterAwareDataSource
spring.datasource.yugabytedb.serverName=localhost
spring.datasource.yugabytedb.portNumber=5433
spring.datasource.yugabytedb.user=yugabyte
spring.datasource.yugabytedb.schema=springpr
#spring.datasource.yugabytedb.pa$$word=
#spring.datasource.yugabytedb.loadBalance=true
#spring.datasource.yugabytedb.additionalEndpoints=127.0.0.2:5433,127.0.0.3:5433,127.0.0.4:5433,127.0.0.5:5433
#spring.datasource.yugabytedb.topologyKeys=cloud1.region1.zone1,cloud1.region2.zone2

spring.datasource.hikari.schema=springpr