### Spring Cloud Data Flow ###
logging.level.org.springframework.cloud.task=DEBUG
# task tables initialization
spring.cloud.task.initialize-enabled=false
spring.cloud.task.tablePrefix=boot3_task_

### Spring Batch ###
# batch tables initialization ALWAYS, EMBEDDED, NEVER
spring.batch.jdbc.initialize-schema=NEVER
#spring.batch.jdbc.platform=
#spring.batch.jdbc.schema=classpath:org/springframework/batch/core/schema-@@platform@@.sql
spring.batch.jdbc.table-prefix=boot3_batch_
spring.batch.job.enabled=false

### Spring JPA ###
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=${spring.jpa.database-platform}
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.default_schema=springpr
spring.jpa.show-sql=true

### Database Initialization
spring.sql.init.platform=postgres
# ALWAYS, EMBEDDED, NEVER
spring.sql.init.mode=NEVER
spring.sql.init.continue-on-error=false
#spring.sql.init.data-locations=classpath*:schema-${platform}.sql
#spring.sql.init.schema-locations=classpath*:data-${platform}.sql.
#spring.sql.init.username=
#spring.sql.init.pa$$word=

### Postgres ###
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=springpr
spring.datasource.username=postgres
#spring.datasource.pa$$word=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

### Connection Pool
spring.datasource.hikari.schema=springpr
spring.datasource.hikari.connectionTestQuery=SELECT 1
spring.datasource.hikari.connectionTimeout=120000
spring.datasource.hikari.idleTimeout=60000
spring.datasource.hikari.leakDetectionThreshold=60000
spring.datasource.hikari.maximumPoolSize=30
spring.datasource.hikari.maxLifetime=3600000
spring.datasource.hikari.minimumIdle=6
spring.datasource.hikari.poolName=casHikariPool
spring.datasource.hikari.validationTimeout=3000

### batch database ###
spring.datasource.batch.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=springpr
spring.datasource.batch.username=postgres
#spring.datasource.batch.pa$$word=postgres
spring.datasource.batch.driver-class-name=org.postgresql.Driver

spring.datasource.batch.hikari.schema=springpr
spring.datasource.batch.hikari.poolName=casHikariPool-database1
spring.datasource.batch.hikari.connectionTestQuery=SELECT 1

### database1 ###
spring.datasource.database1.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=springpr
spring.datasource.database1.username=postgres
#spring.datasource.database1.pa$$word=postgres
spring.datasource.database1.driver-class-name=org.postgresql.Driver

spring.datasource.database1.hikari.schema=springpr
spring.datasource.database1.hikari.poolName=casHikariPool-database1
spring.datasource.database1.hikari.connectionTestQuery=SELECT 1

### Datasource Micrometer o11y ###
jdbc.datasource-proxy.enabled=true
jdbc.datasource-proxy.query.enable-logging=false
jdbc.datasource-proxy.include-parameter-values=true
jdbc.datasource-proxy.logging=slf4j
jdbc.datasource-proxy.query.log-level=ERROR
jdbc.datasource-proxy.multiline=true
jdbc.datasource-proxy.query.logger-name=springpr-jpa.query-logger

# spring boot log level property, the springpr-jpa is defined in line above
logging.level.springpr-jpa.query-logger=DEBUG

### JPA Exception Translation ###
spring.aop.proxy-target-class=true
spring.dao.exceptiontranslation.enabled=true

### Transaction ###
spring.transaction.default-timeout=120
