// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/service/service.proto
// Protobuf Java Version: 4.29.3

package com.service;

public interface GetDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service.GetDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
