##############################
### Concurrency Properties ###
##############################
### Threading/Virtual Threads ###
spring.threads.virtual.enabled=false
spring.task.execution.simple.concurrency-limit=1000
spring.task.scheduling.simple.concurrency-limit=1001
spring.task.scheduling.thread-name-prefix=task-scheduling
spring.task.execution.thread-name-prefix=task-execution
### Async Executor default valuesh, it is used by Tomcat ###
spring.task.execution.pool.allow-core-thread-timeout=true
spring.task.execution.pool.keep-alive=60s
spring.task.execution.pool.core-size=8
spring.task.execution.pool.max-size=16
spring.task.execution.pool.queue-capacity=3600
### Scheduled Tasks ###
spring.task.scheduling.pool.size=5

### Tomcat default setting ###
server.tomcat.accept-count=100
#server.tomcat.connection-timeout=5s
server.tomcat.max-connections=8192
server.tomcat.max-keep-alive-requests=100
server.tomcat.processor-cache=200
server.tomcat.threads.min-spare=10
