#########################################
### OpenTelemetry Spring Boot Starter ###
#########################################
### OpenTelemetry could be disabled fully ###
otel.sdk.disabled=false
### Otel Logging ###
otel.instrumentation.log4j-appender.enabled=true
otel.logs.exporter=otlp
otel.exporter.otlp.logs.timeout=1s
### Otel Metrics ###
otel.metrics.exporter=otlp
otel.exporter.otlp.metrics.timeout=10s
otel.metric.export.interval=1m
### Otel Tracing ###
otel.traces.exporter=otlp
otel.traces.sampler=always_on
otel.experimental.exporter.otlp.retry.enabled=true

### ELF required attributes ###
### Spring Boot 3.2.x configuration
#otel.springboot.resource.attributes.service.car.id=200005782
#otel.springboot.resource.attributes.service.namespace=dev.springpr.springpr
#otel.springboot.resource.attributes.service.instance.id=${springpr.app.id}
#otel.springboot.resource.attributes.deployment.environment=E0

### Spring Boot 3.3.x configuration ###
otel.propagators=tracecontext,b3
otel.resource.attributes.service.name=springpr
otel.resource.attributes.service.car.id=200005782
otel.resource.attributes.service.namespace=dev.springpr.springpr
otel.resource.attributes.service.instance.id=${springpr.app.id}
otel.resource.attributes.deployment.environment=E0

### Spring Boot Default Metrics ###
management.otlp.metrics.export.base-time-unit=milliseconds
management.otlp.metrics.export.batch-size=10000
management.otlp.metrics.export.connect-timeout=10s
management.otlp.metrics.export.enabled=false
management.otlp.metrics.export.read-timeout=10s
management.otlp.metrics.export.step=1m
#management.otlp.metrics.export.url=https://otel.springpr.dev/ot/v1/metrics

# Whether auto-configuration of tracing is enabled to export and propagate traces.
management.tracing.enabled=true
management.otlp.tracing.compression=none
#management.otlp.tracing.endpoint=https://otel.springpr.dev/ot/v1/traces
management.otlp.tracing.timeout=10s
management.tracing.sampling.probability=1.0

### Otle Instrumentation ###
#otel.instrumentation.opentelemetry-instrumentation-annotations.exclude-methods=my.package.MyClass1[method1,method2];my.package.MyClass2[method3]
#otel.instrumentation.methods.include=my.package.MyClass1[method1,method2];my.package.MyClass2[method3]

# Whether observations starting with the specified name should be enabled. 
management.observations.enable.all=true

### Micrometer Metrics ###
management.otlp.metrics.export.url=https://otel.springpr.dev/ot/v1/metrics
management.otlp.metrics.export.enabled=false
management.otlp.metrics.export.step=1m

management.observations.enable.all=true
management.observations.key-values.region=us-ipc2
management.observations.key-values.stack=dev
management.observations.enable.denied.prefix=false
management.observations.enable.another.denied.prefix=false

# log details of spans/metrics data exported
springpr.micrometer.interceptable-span-exporter.enabled=true
springpr.micrometer.interceptable-metric-exporter.enabled=true
