###################################
### Spring PR Common Properties ###
###################################
### SpringPR Micrometer debug properties ###
springpr.micrometer.interceptable-span-exporter.enabled=false
springpr.micrometer.interceptable-metric-exporter.enabled=false

### SpringPR systemMetricsScheduler properties ###
springpr.common.systemMetricsScheduler.enabled=true
springpr.common.systemMetricsScheduler.sampling.cron=*/10 * * * * *

### SpringPR Retry ### ###
springpr.base.retry.intialInterval=100
springpr.base.retry.maxInterval=60000
springpr.base.retry.multiplier=2
springpr.base.retry.totalRetries=16

### SpringPR asyncTaskExecutor ###
async.handler.concurrency=3
async.queue.capacity=3500

### SpringPR File Health Indicator ###
required.file.check.enabled=false
required.file.absolute.path=/Users/yli25/Downloads/STS4/springpr/${app.id}/lombok.config

### Maven inheritance test properties ###
maven.parent.property=${parent_property}
maven.child.property=${child_property}
