########################
### Spring Data REST ###
########################
spring.data.rest.basePath=/api/v1
spring.data.rest.defaultPageSize=100
spring.data.rest.maxPageSize=1000
spring.data.rest.returnBodyOnCreate=true
spring.data.rest.returnBodyOnUpdate=true

### Pagination ###
spring.data.web.pageable.default-page-size=100
spring.data.web.pageable.max-page-size=100
# Pagination parameter customization 
#/employees?page_chunk=1&page_limit=30.
#spring.data.web.pageable.page-parameter=chunk
#spring.data.web.pageable.size-parameter=limit
#spring.data.web.pageable.prefix=page

### REST API response ###
server.error.include-message=ALWAYS
#server.error.whitelabel.enabled=false
error.handling.http-status-in-json-response=true
#spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES: true
