###################################
### Application Deployment Info ###
###################################
### Configure welcome landing page URL ###
app.id=${springpr.app.id}
app.protocol=https
app.service=restexamplev001
app.domain=org.springpr
app.env.id=dev
app.hostname=${app.service}-${app.env.id}.${app.domain}
app.port=443
app.zone.id=eusw1a4
app.zone.hostname=${app.service}-${app.env.id}${app.zone.id}.${app.domain}
springpr.openapi.server.url=${app.protocol}://${app.zone.hostname}:${app.port}
