###################################
### Spring Properties ###
###################################
# active Spring profile, values are from Maven profile
spring.profiles.active=${springboot.profiles}
spring.application.name=${springpr.app.id}
spring.main.banner-mode=console
spring.main.allow-bean-definition-overriding=false
spring.main.allow-circular-references=false
spring.main.keep-alive=false
# Spring Boot debug enabled
#debug=true
#trace=true
spring.jmx.enabled=true
### devtools ###
spring.devtools.restart.enabled=false
