<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springpr.springpr</groupId>
    <artifactId>springpr-server-parent-pom</artifactId>
    <version>${revision}</version>
    <relativePath>../springpr-parent-bom/springpr-parent-pom/springpr-server-parent-pom</relativePath>
  </parent>

  <artifactId>springpr-common-parent</artifactId>
  <packaging>pom</packaging>
  <description>See README.md</description>

  <modules>
    <module>springpr-common-template-test</module>
    <module>springpr-common-template</module>
  </modules>

  <properties>
    <git-commit-id-maven-plugin.skip>false</git-commit-id-maven-plugin.skip>
    <spotless-maven-plugin.skip>false</spotless-maven-plugin.skip>
  </properties>
</project>
