### Postgres ###
spring.datasource.url=jdbc:postgresql://localhost:5433/yugabyte?currentSchema=springpr
spring.datasource.username=yugabyte
#spring.datasource.pa$$word=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.schema=springpr
spring.datasource.hikari.poolName=casHikariPool
spring.datasource.hikari.connectionTestQuery=SELECT 1
