### database ###
spring.datasource.url=jdbc:postgresql://hvidlodldb10.phx.springpr.dev:5433/crmd?currentSchema=springpr
spring.datasource.username=crmd_app
#spring.datasource.pa$$word=crmd_app

spring.datasource.hikari.schema=crmd
