spring.datasource.yugabytedb.databaseName=yugabyte

spring.datasource.yugabytedb.serverName=localhost
spring.datasource.yugabytedb.portNumber=5433
spring.datasource.yugabytedb.user=yugabyte
spring.datasource.yugabytedb.pa$$word=
spring.datasource.yugabytedb.loadBalance=false
spring.datasource.yugabytedb.additionalEndpoints=
spring.datasource.yugabytedb.topologyKeys=
