// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/service/service2.proto
// Protobuf Java Version: 4.29.3

package com.service2;

public interface GetDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.GetDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
