// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/service/service2.proto
// Protobuf Java Version: 4.29.3

package com.service2;

public interface GetDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.GetDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string data = 1;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>required string data = 1;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>required string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
