### local dev ###
server.port=60207

# ELF attribute
otel.resource.attributes.service.name=springpr-yugabytedb
otel.resource.attributes.service.car.id=150838830
otel.resource.attributes.service.namespace=org.springpr.springpr.yugabytedb
otel.resource.attributes.service.instance.id=${springpr.app.id}
otel.resource.attributes.deployment.environment=E0

otel.exporter.otlp.protocol=grpc
otel.exporter.otlp.endpoint=https://otel.springpr.org
