### database ###
spring.datasource.url=jdbc:postgresql://localhost:5433/yugabyte?currentSchema=springpr
spring.datasource.username=yugabyte
#spring.datasource.database1.pa$$word=postgres

spring.datasource.hikari.schema=springpr
