### local dev ###
server.port=9091

#local is a channel name used in 
spring.grpc.client.channels.local.address=localhost:9090
#There is a default named channel that you can configure as 
#spring.grpc.client.default-channel.*, and then it will be used by default 
#if there is no channel with the name specified in the channel creation.
spring.grpc.client.default-channel.address=static://localhost:9090
#
#spring.grpc.client.default-channel.address=static://localhost:9090
#spring.grpc.client.default-channel.default-load-balancing-policy=round_robin
#spring.grpc.client.default-channel.enable-keep-alive=true
#spring.grpc.client.default-channel.health.enabled=true
#
#spring.grpc.client.channels.originChannel.health.enabled=true
#spring.grpc.client.channels.originChannel.health.service-name=grpcHelloService

spring.devtools.restart.enabled=true

spring.grpc.client.enabled=true

spring.grpc.client.default-channel.health.enabled=true
spring.grpc.client.channels.local.health.enabled=true
spring.grpc.client.channels.local.health.service-name=grpc.v1.GrpcHelloService