### OAuth 2.0
spring.security.oauth2.client.registration.springpr.client-id=your-google-client-id
spring.security.oauth2.client.registration.springpr.client-secret=your-google-client-secret
spring.security.oauth2.client.registration.springpr.scope=- profile
spring.security.oauth2.client.provider.springpr.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.springpr.token-uri=https://www.googleapis.com/oauth2/v4/token
spring.security.oauth2.client.provider.springpr.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.springpr.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
