#logging.level.org.springframework.data.cassandra.core.cql.CqlTemplate=DEBUG
#logging.level.com.datastax.driver.core.QueryLogger.NORMAL=DEBUG
#logging.level.com.datastax.driver.core.QueryLogger.SLOW=TRACE

springpr.config.property=test-value

### SpringPR WebClient Properties
logging.level.reactor.netty.http.client.HttpClient=DEBUG

springpr.common.sampling.cron=0 * * * * ?

spring.grpc.server.health.enabled=true
spring.grpc.server.reflection.enabled=true
spring.grpc.server.observations.enabled=true
spring.grpc.server.servlet.enabled=true
spring.grpc.server.exception-handling.enabled=true

#springpr.webclient.zone.hostname=${app.hostname}
#
#springpr.webclient.default.base-uri=http://localhost:60201/
#springpr.webclient.default.defaultHttpExchangeClientClassname=dev.springpr.springpr.webclient.example.emoloyee.client.EmployeeClient
#
#springpr.webclient.httpclient-logging-enabled=true
#springpr.webclient.keepalive=true
#springpr.webclient.connect-timeout-mills=1000
#springpr.webclient.response-timeout-mills=1000
#springpr.webclient.read-timeout-mills=1000
#springpr.webclient.write-timeout-mills=1000
#springpr.webclient.max-connections=5000
#
