### local dev ###
server.port=9090

# ELF attribute
otel.resource.attributes.service.name=springpr-grpc
otel.resource.attributes.service.car.id=150838830
otel.resource.attributes.service.namespace=dev.springpr.springpr.grpc
otel.resource.attributes.service.instance.id=${springpr.app.id}
otel.resource.attributes.deployment.environment=E0

otel.exporter.otlp.protocol=grpc
otel.exporter.otlp.endpoint=https://otel.springpr.dev

spring.devtools.restart.enabled=true

spring.grpc.client.channels.local.address=0.0.0.0:9090
spring.grpc.client.default-channel.address=0.0.0.0:9090

#spring.grpc.server.address=static://localhost:9090
spring.grpc.server.health.enabled=true
#spring.grpc.server.host=*
#spring.grpc.server.port=9090
spring.grpc.server.inprocess.exclusive=true
spring.grpc.server.exception-handling.enabled=true
spring.grpc.server.observations.enabled=true
spring.grpc.server.reflection.enabled=true
spring.grpc.server.servlet.enabled=true

spring.grpc.client.enabled=false
spring.grpc.client.inprocess.enabled=true
spring.grpc.client.inprocess.exclusive=true
